### ISSUE TITLE
Do you want a Fedora package?

### ISSUE THREAD

**Issue by 0xMRTT** [AndroGR/CleanerApp#1]
I would be happy to create a Fedora package for your project because you taked part in gradience

**Comment by AndroGR** [comment]
Hello,
I currently don't plan to distribute the application as a package installable by `apt`, `dnf` etc. Being fairly honest I don't work on it much, I just created it to play around with Gtk4 and libadwaita.

**Comment by 0xMRTT** [comment]
Okay, good luck 🤞
